### ISSUE TITLE
One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric.

### ISSUE THREAD

**Issue by sgs00** [GoogleCloudPlatform/tensorflow-inference-tensorrt5-t4-gpu#3]
Hi, I'm trying to use report_gpu_metrics.py as described at https://cloud.google.com/compute/docs/gpus/monitor-gpus, but I'm getting the following error:

```
root@instance-3:~# python /root/report_gpu_metrics.py
Traceback (most recent call last):
  File "/root/report_gpu_metrics.py", line 86, in <module>
    project_id)
  File "/root/report_gpu_metrics.py", line 49, in report_metric
    client.create_time_series(project_name, [series])
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/monitoring_v3/gapic/metric_service_client.py", line 1039, in create_time_series
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/usr/lib/python2.7/dist-packages/six.py", line 737, in raise_from
    raise value
google.api_core.exceptions.InvalidArgument: 400 One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/gpu_utilization, Timestamps: {Youngest Existing: '2020/04/07-15:41:27.431', New: '2020/04/07-15:41:28.941'}}: timeSeries[0]
root@instance-3:~#
```

**Comment by sgs00** [comment]
Sorry, I was trying to manually run the script while it was running trough systemd.
